#!/bin/sh
flag_test=$(git config flags.run-tests)
flag_extract_version=$(git config flags.extract-version)
flag_push_to_nuget=$(git config flags.push-to-nuget)

if [ -n $flag_test ] && [ "$flag_test" = "true" ]; then
	echo "running tests..."
	result=$(./run-dotnet-tests.sh | tee /dev/tty)
	if [ $? -ne 0 ]; then
		echo "ERROR: failed running tests with error code: $?"
		exit 1;
	fi
fi

if [ -n $flag_extract_version ] && [ "$flag_extract_version" = "true" ]; then
	echo "extracting version..."
	result=$(./extract-dotnet-project-version.sh)
	if [ $? -ne 0 ]; then
		echo "ERROR: failed extracting version with error code: $?"
		exit 2;
	fi
	version=$result
	echo "Extracted version '$version'"
fi

if [ -n $flag_extract_version ] && [ "$flag_extract_version" = "true" ]; then
	echo "pushing to nuget..."
	result=$(./nuget-push.sh $version | tee /dev/tty)
	if [ $? -ne 0 ]; then
		echo "ERROR: failed pushing to nuget with error code: $?"
		exit 3;
	fi
fi
exit 0;


echo "[Pre Merge] SUCCESS: Continuing with push..."
